// scripts/generate-assets.js
import fs from 'fs';
import path from 'path';

const ASSETS_DIR = path.resolve('src/assets');
const OUTPUT_FILE = path.resolve('src/assets/asset-manifest.js');
const DTS_OUTPUT_FILE = path.resolve('src/assets/asset-manifest.d.ts');

// Correctly converts `crescent-isle-1.png` to `crescentIsle1`
const toCamelCase = (str) => {
  return str.replace(/\.(.+)$/, '').replace(/[-]([a-z0-9])/g, (g) => g[1].toUpperCase());
};

const generateAssetManifest = (dir, basePath = []) => {
  let manifest = {};
  const items = fs.readdirSync(dir);

  items.forEach((item) => {
    const fullPath = path.join(dir, item);
    const stat = fs.statSync(fullPath);
    // Use the base item name for the key
    const key = toCamelCase(item);

    if (stat.isDirectory()) {
      manifest[key] = generateAssetManifest(fullPath, [...basePath, item]);
    } else {
      // Create a relative path from the /src directory
      const relativePath = path.join('/src/assets', ...basePath, item).replace(/\\/g, '/');
      // Create a function that uses `new URL` which Vite will process.
      manifest[key] = `() => new URL('${relativePath}', import.meta.url).href`;
    }
  });

  return manifest;
};

const manifest = generateAssetManifest(ASSETS_DIR);

// Custom JSON stringify to handle function strings
const jsonStringifyWithFunctions = (obj, indent = 2) => {
  const replacer = (key, value) => {
    if (typeof value === 'string' && value.startsWith('() =>')) {
      return `%%FUNCTION%%${value}%%FUNCTION%%`;
    }
    return value;
  };

  let json = JSON.stringify(obj, replacer, indent);
  
  // Replace placeholders with actual functions
  json = json.replace(/"%%FUNCTION%%(.*?)%%FUNCTION%%"/g, (match, funcStr) => {
    return funcStr.replace(/\\"/g, '"').replace(/\\\\/g, '\\');
  });

  return json;
};

const fileContent = `// This file is auto-generated by generate-assets.js\n// Do not edit manually.\n\nexport const assets = ${jsonStringifyWithFunctions(manifest, 2)};`;

const dtsContent = `// This file is auto-generated by generate-assets.js\n// Do not edit manually.\n\ndeclare module '@assets' {\n  export const assets: any;\n}\n`;

fs.writeFileSync(OUTPUT_FILE, fileContent);
fs.writeFileSync(DTS_OUTPUT_FILE, dtsContent);

console.log(`Asset manifest generated at ${OUTPUT_FILE}`);
console.log(`TypeScript declarations generated at ${DTS_OUTPUT_FILE}`);