// scripts/generate-assets.js
import fs from 'fs';
import path from 'path';

const ASSETS_DIR = path.resolve('public/assets');
const OUTPUT_FILE = path.resolve('src/assets/asset-manifest.js');
const DTS_OUTPUT_FILE = path.resolve('src/assets/asset-manifest.d.ts');

// Convert `crescent-isle-1.png` → `crescentIsle1`
const toCamelCase = (str) => {
  return str.replace(/\.(.+)$/, '').replace(/[-]([a-z0-9])/g, (g) => g[1].toUpperCase());
};

const generateAssetManifest = (dir, basePath = []) => {
  let manifest = {};
  const items = fs.readdirSync(dir);

  items.forEach((item) => {
    const fullPath = path.join(dir, item);
    const stat = fs.statSync(fullPath);
    const key = toCamelCase(item);

    if (stat.isDirectory()) {
      manifest[key] = generateAssetManifest(fullPath, [...basePath, item]);
    } else {
      // Build a direct public URL
      const publicUrl = path
        .join('assets', ...basePath, item)
        .replace(/\\/g, '/');

      // Just return raw URL string — no import needed
      manifest[key] = publicUrl;
    }
  });

  return manifest;
};

const manifest = generateAssetManifest(ASSETS_DIR);

const fileContent = `// This file is auto-generated by generate-assets.js
// Do not edit manually.

export const assets = ${JSON.stringify(manifest, null, 2)};`;

const dtsContent = `// This file is auto-generated by generate-assets.js
// Do not edit manually.

declare module '@assets' {
  export const assets: any;
}
`;

fs.writeFileSync(OUTPUT_FILE, fileContent);
fs.writeFileSync(DTS_OUTPUT_FILE, dtsContent);

console.log(`Asset manifest generated at ${OUTPUT_FILE}`);
console.log(`TypeScript declarations generated at ${DTS_OUTPUT_FILE}`);
